### PR TITLE
test: manual test failing

### PR DESCRIPTION
**Pull request by ptmminh**
This part fails due to KeyError for me.

### CODE REVIEW

**Comment by elliot-100** [comment]
Can you be more specific about why it's failing e.g. with an anonymised extract from message data? Interested as I plan to look at messaging next.

**Comment by ptmminh** [comment]
Yeah sure, for some reason, `"text"` is not a valid key in `message["message"]`. This was a group text though

**Review by elliot-100 — APPROVED** [review]
Works fine on my live data.

**Comment by elliot-100** [comment]
Great - this tells us a bit more about variations in chat/message data structures, which at a glance do appear more complex than groups, events, etc. Merging.

**Pull request merged**
