### PR TITLE
Update `send_message()` README documentation to reflect ability to start a new chat

### PR DESCRIPTION
**Pull request by elliot-100**
@olizimmermann this relates to your https://github.com/Olen/Spond/pull/62 - do you have any comments?

### CODE REVIEW

**Comment by Olen** [comment]
Just a question - is it possible to only specify user, or is group_id a requirement in the API?

**Comment by elliot-100** [comment]
> Just a question - is it possible to only specify user, or is group_id a requirement in the API?

Implementation requires both:

```
elif group_uid is None or user is None:
    return {
        "error": "wrong usage, group_id and user_id needed or continue chat with chat_id"
        }
```
Not sure why an actual Exception isn't raised.

**Comment by olizimmermann** [comment]
I will push an update next week. Currently afk

**Comment by Olen** [comment]
Yeah.  We should merge this as it is only documentation.  And the we can update the actual function later.

**Comment by olizimmermann** [comment]
Hey guys, 
Thanks for updating the docstring/readme.

**Pull request merged**
