### PR TITLE
Add: `subgroup_id` parameter to `get_events()` API call

### PR DESCRIPTION
**Pull request by elliot-100**
Includes README update.
Can't think of a simple way to add tests/manual pseudo-tests for this.

### CODE REVIEW

**Comment by ptmminh** [comment]
Looks good as long as the manual test runs through successfully!

Slight nit picky but the second commit should probably be `feat` since `add` is not a keyword. See more [here](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type) but can be merged without fixing.

**Comment by Olen** [comment]
Looks good to me

**Comment by Olen** [comment]
This should be meged before #107 and #107 must probably be rebased after merge.

**Comment by elliot-100** [comment]
> Slight nit picky but the second commit should probably be `feat` since `add` is not a keyword.

Fair - will adhere to this (or similar - there are a few variations) next time.

**Pull request merged**
