### PR TITLE
fix: meaningful error when authentication fails

### LINKED ISSUE #83: When authentication fails, error isn't meaningful and session/connector isn't closed.
Re: https://github.com/Olen/Spond/issues/82, we don't handle authentication failures well:
```
Traceback (most recent call last):
...
  File "/home/[redacted]/lib/python3.10/site-packages/spond/spond.py", line 67, in get_group
    await self.login()
  File "/home/[redacted]/lib/python3.10/site-packages/spond/spond.py", line 25, in login
    self.cookie = r.cookies["auth"]
KeyError: 'auth'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f29ff876470>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f29ff8824a0>, 11274797.606713338)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f29ff875a50>

2023-08-07 23:27:12 -- Completed task, took 6.65 seconds, return code was 1.
```

### PR DESCRIPTION
**Pull request by ptmminh**
Fixes #83

Example error:

```
$ python groups.py 
Traceback (most recent call last):
  File "/home/<redacted>/Spond/groups.py", line 33, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/<redacted>/Spond/groups.py", line 14, in main
    groups = await s.get_groups()
  File "/home/<redacted>/Spond/spond/spond.py", line 60, in wrapper
    raise e
  File "/home/<redacted>/Spond/spond/spond.py", line 57, in wrapper
    await self.login()
  File "/home/<redacted>/Spond/spond/spond.py", line 41, in login
    raise AuthenticationError(err_msg)
spond.spond.AuthenticationError: Login failed. Response received: {'errorKey': 'wrongEmailOrPassword', 'message': 'Wrong email or password.'}
```

### CODE REVIEW

**Comment by elliot-100** [comment]
Thanks for this @ptmminh.

I think the `ValueError` should be a more specific `AuthenticationError`.

e.g.

```
class AuthenticationError(Exception)
  pass
...
raise AuthenticationError(err_msg)

```

I don't know enough about `aiohttp` to work out the 'Unclosed connector' problem, but can be dealt with separately; this pull request delivers value without it.

**Comment by Olen** [comment]
Since the login now raises an exception, this exception should be caught by the functons that calls the login function.

To close the connector, all you need to do is catch the exception and do someting like
```
    except AuthenticationError:
        print("Authentication error")
        await s.clientsession.close()
        sys.exit()
```

**Comment by ptmminh** [comment]
Thanks @elliot-100 and @Olen for the review! All very helpful remarks, I've made adjustments based on your suggestions. Now the connector even closes!

I also created a decorator to handle the authentication check to avoid duplicated code in each method that calls `login`

**Comment by Olen** [comment]
Great work.
The repo and workflows could probably be improved. It was just my personal little thing for a long time, but with more contributions more structure would be good.

@elliot-100 already made a lot of improvements in this regard, and I am grateful for that.

**Comment by Olen** [comment]
It even passes the new test-script @elliot-100 just added.

**Pull request merged**
