### PR TITLE
added option to start a new chat or continue old one

### PR DESCRIPTION
**Pull request by olizimmermann**

### CODE REVIEW

**Review by Olen — COMMENTED** [review]
I like it. But I think we should either merge it with the current `send_message`  or give it a different name, so it is more clear where the two functions differ.

And could we simplify the two functions if they are mergeable, so it could somehow autodetect if the recepient is a chat_id, a group_uid or a user?

**Comment by elliot-100** [comment]
@olizimmermann or @Olen do you plan to progress this? I don't know enough about chats myself.

**Comment by olizimmermann** [comment]
What exactly do you need? Check out my latest PR.

**Comment by elliot-100** [comment]
Can you resolve the conficts in your branch? I think I can then merge it.

**Comment by elliot-100** [comment]
Thanks @olizimmermann! @Olen I've gone ahead and merged since you already reviewed the bulk of this - hope that's OK.

**Pull request merged**
