### PR TITLE
added update_event function

### PR DESCRIPTION
**Pull request by olizimmermann**
Just added an update option for events. Submitting soon a create function as well.

Cheers

### CODE REVIEW

**Review by Olen — COMMENTED** [review]
Just thinking and wanting to hear your opinion.  Would it be better if the function fetched the original event itself?
If you always have to supply the original event in addition to the changes, this sounds to me like a better way than having to do it manually before creating the changes?

**Comment by olizimmermann** [comment]
Good idea. Let me test it.

**Comment by Olen** [comment]
If you like, please also look at #57 and add some comments.

**Comment by olizimmermann** [comment]
@Olen updated it :)

**Pull request merged**
