### PR TITLE
Changed: raise `KeyError` instead of `IndexError` for all failed lookup methods

### PR DESCRIPTION
**Pull request by elliot-100**
For `get_person()`, also make error message more meaningful and add 'Raises' to docstring.

### CODE REVIEW

**Comment by elliot-100** [comment]
Let me know if any comments.

@dhomeier: relates to your PR #134

**Comment by elliot-100** [comment]
Oops, should be be changing to 'KeyError' of course. Will revise.

**Comment by elliot-100** [comment]
Is it OK if I merge this @Olen?

**Comment by Olen** [comment]
Looks fine

**Pull request merged**
